[package]
name = "ninja"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40", features = ["full"] }
toml = "0.8"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "symbols"
